### ISSUE TITLE
替换yolov8Conv报错

### ISSUE THREAD

**Issue by JackyCs13** [cheng-haha/ScConv#17]
请问为什么我直接替换yolov8的Conv会出现报错
Traceback (most recent call last):
  File "/home/ubuntu/ultralytics-main/Mytrain.py", line 4, in <module>
    model = YOLO("/home/ubuntu/ultralytics-main/ultralytics/cfg/models/v8/yolov8_test.yaml")  # 从头开始构建新模型
  File "/home/ubuntu/ultralytics-main/ultralytics/engine/model.py", line 89, in __init__
    self._new(model, task)
  File "/home/ubuntu/ultralytics-main/ultralytics/engine/model.py", line 118, in _new
    self.model = (model or self._smart_load('model'))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "/home/ubuntu/ultralytics-main/ultralytics/nn/tasks.py", line 233, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
  File "/home/ubuntu/ultralytics-main/ultralytics/nn/tasks.py", line 689, in parse_model
    m_ = nn.Sequential(*(m(*args) for _ in range(n))) if n > 1 else m(*args)  # module
  File "/home/ubuntu/ultralytics-main/ultralytics/nn/modules/conv.py", line 856, in __init__
    self.CRU = CRU( op_channel, 
  File "/home/ubuntu/ultralytics-main/ultralytics/nn/modules/conv.py", line 820, in __init__
    self.squeeze2       = nn.Conv2d(low_channel,low_channel//squeeze_radio,kernel_size=1,bias=False)
  File "/home/ubuntu/anaconda3/envs/v8/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 450, in __init__
    super().__init__(
  File "/home/ubuntu/anaconda3/envs/v8/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 137, in __init__
    self.weight = Parameter(torch.empty(
RuntimeError: Trying to create tensor with negative dimension -64: [-64, -128, 1, 1]

**Comment by jiangyangbo** [comment]
出现，一样的错误

**Comment by ghostmiao5** [comment]
一样

**Comment by luoni123** [comment]
请问大家解决了吗？

**Comment by ghostmiao5** [comment]
你好，邮件收到了，会尽快回复。
